apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-admin
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: 738983679783.dkr.ecr.us-east-1.amazonaws.com/library-admin:cfbf26f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: library
spec:
  type: LoadBalancer
  selector:
    app: admin
  ports:
    - port: 3001
      targetPort: 80
