apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 738983679783.dkr.ecr.ap-south-1.amazonaws.com/library-backend:0eb7d24
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/libraryDB
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: library
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
