apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-backend
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/library-backend:c520db8
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/libraryDB
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: library
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
