apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
  namespace: library
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 301678011164.dkr.ecr.us-east-1.amazonaws.com/library-frontend:c3d5215
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: library
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80        # External port (LoadBalancer)
      targetPort: 80  # Container port (nginx)
